name: Deploy Bicep

on: [push, workflow_dispatch]

jobs:
  jobA:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
    - name: Hard-Coded Outputs
      id: bicep-outputs
      run: |
        echo "Hard-coded outputs:"
        echo "acrName=Blah123" >> $GITHUB_OUTPUT
        #echo "acrName=Blah123" | Out-File -Append $env:GITHUB_OUTPUT
    outputs: 
      acrName: ${{ steps.bicep-outputs.outputs.acrName }}
  
  jobB:
    runs-on: ubuntu-latest
    needs: jobA
    defaults:
      run:
        shell: pwsh
    steps:
      - run: |
          Write-Host "ACR Name -> " ${{ needs.jobA.outputs.acrName }}
