name: Deploy Bicep

on: [push, workflow_dispatch]

jobs:
  jobA:
    # uses: delarooster/Dlr.Yaml.Templates/.github/workflows/deploy-bicep.yaml@main
    # with:
    #     bicepTemplatePath: 'env/main.bicep'
    #     clientAffix: 'Test test 123'
    #     env: 'Ts'
    #     resourceGroup: 'rg-atd-test'
    # secrets: inherit
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
    - name: Hard-Coded Outputs
      id: bicep-outputs
      run: |
        echo "Hard-coded outputs:"
        echo "acrName=Blah123" >> $GITHUB_OUTPUT
        echo "acrName=Blah123" | Out-File -Append $env:GITHUB_OUTPUT
        echo "acrName=Blah123" >> $GITHUB_ENV
        echo "acrName=Blah123" | Out-File -Append $env:GITHUB_ENV
    outputs: 
      acrName: ${{ steps.bicep-outputs.outputs.acrName }}
  
  jobB:
    runs-on: ubuntu-latest
    needs: jobA
    defaults:
      run:
        shell: pwsh
    steps:
      - run: |
          Write-Host "ACR Name -> " ${{ needs.jobA.outputs.acrName }}
          Write-Host "ACR Name -> " ${{ needs.jobA.bicep-outputs.outputs.acrName }}
          Write-Host "ACR Name -> " ${{ needs.bicep-outputs.outputs.acrName }}
