name: Deploy Bicep

on: [push, workflow_dispatch]

jobs:
  inputs:
    uses: delarooster/Dlr.Yaml.Templates/.github/workflows/deploy-bicep.yaml@main
    with:
        bicepTemplatePath: 'env/main.bicep'
        additionalBicepParameters: |
          clientAffix: 
        clientAffix: 'Test test 123'
        env: 'Ts'
        resourceGroup: 'rg-atd-test'
    secrets: inherit