name: Deploy Bicep

on: [push, workflow_dispatch]

jobs:
  jobA:
    uses: delarooster/Dlr.Yaml.Templates/.github/workflows/deploy-bicep.yaml@main
    with:
        bicepTemplatePath: 'env/main.bicep'
        clientAffix: 'Test test 123'
        env: 'Ts'
        resourceGroup: 'rg-atd-test'
    secrets: inherit
  
  jobB:
    runs-on: ubuntu-latest
    needs: jobA
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: bicep-outputs
          
      - name: Display structure of downloaded files
        run: ls -R
        
      - run: |
          Write-Host "ACR Name -> " $(Get-Content -Path bicep-outputs/acrName)