name: Deploy Bicep

on: [push, workflow_dispatch]

jobs:
  deploy:
    uses: delarooster/Dlr.Yaml.Templates/.github/workflows/deploy-bicep.yaml@main
    with:
      bicepTemplatePath: "env/main.bicep"
      clientAffix: "Test test 123"
      env: "Ts"
      resourceGroup: "rg-atd-test"
    secrets: inherit

  post-deploy:
    runs-on: ubuntu-latest
    needs: deploy
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: bicep-outputs
          path: bicep-outputs

      - name: Display structure of downloaded files
        run: ls -R

      - name: ACR Name Check
        run: |
          Write-Host "ACR Name -> " $(Get-Content -Path bicep-outputs/acrName)
