name: Deploy Bicep

on: [push, workflow_dispatch]

jobs:
  inputs:
    uses: delarooster/Dlr.Yaml.Templates/.github/workflows/deploy-bicep.yaml@main
    with:
        bicepTemplatePath: 'env/main.bicep'
        clientAffix: 'Test test 123'
        env: 'Ts'
        resourceGroup: 'rg-atd-test'
    secrets: inherit
  
  outputs:
    runs-on: ubuntu-latest
    needs: inputs
    defaults:
      run:
        shell: pwsh
    steps:
      - run: |
          Write-Host "ACR Name -> " ${{ needs.inputs.deploy-bicep.outputs.acrName }}